<h2>What are Custom Exceptions in Python?</h2>
<p>Python <strong>custom exceptions</strong> are user-defined error classes that extend the base Exception class. Developers can define and handle specific error conditions that are unique to their application. Developers can improve their code by creating custom exceptions. This allows for more meaningful error messages and facilitates the debugging process by indicating what kind of error occurred and where it originated.</p>
<p>To define a unique exception we have to typically create a new class that takes its name from Python's built-in Exception class or one of its subclasses. A corresponding except block can be used to raise this custom class and catch it.</p>
<p>Developers can control the flow of the program when specific errors occur and take appropriate actions such as logging the error, retrying operations or gracefully shutting down the application. Custom exceptions can carry additional context or data about the error by overriding the <strong>__init__</strong> method and storing extra information as instance attributes.</p>
<p>Using custom exceptions improves the clarity of error handling in complex programs. It helps to distinguish between different types of errors that may require different handling strategies. For example when a file parsing library might define exceptions like FileFormatError, MissingFieldError or InvalidFieldError to handle various issues that can arise during file processing. This level of granularity allows the client code to catch and address specific issues more effectively by improving the robustness and user experience of the software. Python's custom exceptions are a great tool for handling errors and writing better with more expressive code.</p>
<div class="inserted-div">&nbsp;</div>
<h2>Why to Use Custom Exceptions?</h2>
<p>Custom exceptions in Python offer several advantages which enhances the functionality, readability and maintainability of our code. Here are the key reasons for using custom exceptions &minus;</p>
<ul class="list">
<li><strong>Specificity:</strong> Custom exceptions allow us to represent specific error conditions that are unique to our application.</li>
<li><strong>Clarity:</strong> They make the code more understandable by clearly describing the nature of the errors.</li>
<li><strong>Granularity:</strong> Custom exceptions allow for more precise error handling.</li>
<li><strong>Consistency:</strong> They help to maintain a consistent error-handling strategy across the codebase.</li>
</ul>
<h2>Creating Custom Exceptions</h2>
<p>Creating <strong>custom exceptions</strong> in Python involves defining new exception classes that extend from Python's built-in Exception class or any of its subclasses. This allows developers to create specialized error types that cater to specific scenarios within their applications. Here's how we can create and use custom exceptions effectively &minus;</p>
<h3>Define the Custom Exception Class</h3>
<p>We can start creating the custom exceptions by defining a new class that inherits from <span class="tp-codespan">Exception</span> or another exception class such as <span class="tp-codespan">RuntimeError</span>, <span class="tp-codespan">ValueError</span>, etc. depending on the nature of the error.</p>
<p>Following is the example of defining the custom exception class. In this example CustomError is a custom exception class that inherits from Exception. The <strong>__init__ method</strong> initializes the exception with an optional error message &minus;</p>
<div class="code-mirror  language-python" style="outline: none; overflow-wrap: break-word; overflow-y: auto; white-space: pre-wrap;" contenteditable="plaintext-only" spellcheck="false"><span class="token keyword">class</span> <span class="token class-name">CustomError</span><span class="token punctuation">(</span>Exception<span class="token punctuation">)</span><span class="token punctuation">:</span> <span class="token keyword">def</span> <span class="token function">__init__</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> message<span class="token punctuation">)</span><span class="token punctuation">:</span> <span class="token builtin">super</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>__init__<span class="token punctuation">(</span>message<span class="token punctuation">)</span> self<span class="token punctuation">.</span>message <span class="token operator">=</span> message</div>
<h3>Raise the Custom Exception</h3>
<p>To raise the custom exception we can use the raise statement followed by an instance of our custom exception class. Optionally we can pass a message to provide context about the error.</p>
<p>In this function <strong>process_data()</strong> the CustomError exception is raised when the data parameter is empty by indicating a specific error condition.</p>
<div class="code-mirror  language-python" style="outline: none; overflow-wrap: break-word; overflow-y: auto; white-space: pre-wrap;" contenteditable="plaintext-only" spellcheck="false"><span class="token keyword">def</span> <span class="token function">process_data</span><span class="token punctuation">(</span>data<span class="token punctuation">)</span><span class="token punctuation">:</span> <span class="token keyword">if</span> <span class="token keyword">not</span> data<span class="token punctuation">:</span> <span class="token keyword">raise</span> CustomError<span class="token punctuation">(</span><span class="token string">"Empty data provided"</span><span class="token punctuation">)</span> <span class="token comment"># Processing logic here</span></div>
<h3>Handle the Custom Exception</h3>
<p>To handle the custom exception we have to use a <a href="/python/python_tryexcept_block.htm" target="_blank">try-except block</a>. Catch the custom exception class in the except block and handle the error as needed.</p>
<p>Here in the below code if <strong>process_data([])</strong> raises a CustomError then the except block catches it and we can print the error message (e.message) or perform other error-handling tasks.</p>
<div class="code-mirror  language-python" style="outline: none; overflow-wrap: break-word; overflow-y: auto; white-space: pre-wrap;" contenteditable="plaintext-only" spellcheck="false"><span class="token keyword">try</span><span class="token punctuation">:</span> process_data<span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token keyword">except</span> CustomError <span class="token keyword">as</span> e<span class="token punctuation">:</span> <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f"Custom Error occurred: </span><span class="token interpolation"><span class="token punctuation">{</span>e<span class="token punctuation">.</span>message<span class="token punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span> <span class="token comment"># Additional error handling logic</span></div>
<h2>Example of Custom Exception</h2>
<p>Following is the basic example of custom exception handling in Python. In this example we define a custom exception by subclassing the built-in Exception class and use a try-except block to handle the custom exception &minus;</p>
<div class="code-wrapper">
<div class="code-header">
<div class="logo-side">&nbsp;</div>
<div class="button-side">
<div class="execute">&nbsp;</div>
<div class="open-compiler">Open Compiler</div>
</div>
</div>
<div class="code-mirror  language-python" style="outline: none; overflow-wrap: break-word; overflow-y: auto; white-space: pre-wrap;" contenteditable="plaintext-only" spellcheck="false"><span class="token comment"># Define a custom exception</span> <span class="token keyword">class</span> <span class="token class-name">CustomError</span><span class="token punctuation">(</span>Exception<span class="token punctuation">)</span><span class="token punctuation">:</span> <span class="token keyword">def</span> <span class="token function">__init__</span><span class="token punctuation">(</span>self<span class="token punctuation">,</span> message<span class="token punctuation">)</span><span class="token punctuation">:</span> self<span class="token punctuation">.</span>message <span class="token operator">=</span> message <span class="token builtin">super</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>__init__<span class="token punctuation">(</span>self<span class="token punctuation">.</span>message<span class="token punctuation">)</span> <span class="token comment"># Function that raises the custom exception</span> <span class="token keyword">def</span> <span class="token function">check_value</span><span class="token punctuation">(</span>value<span class="token punctuation">)</span><span class="token punctuation">:</span> <span class="token keyword">if</span> value <span class="token operator">&lt;</span> <span class="token number">0</span><span class="token punctuation">:</span> <span class="token keyword">raise</span> CustomError<span class="token punctuation">(</span><span class="token string">"Value cannot be negative!"</span><span class="token punctuation">)</span> <span class="token keyword">else</span><span class="token punctuation">:</span> <span class="token keyword">return</span> <span class="token string-interpolation"><span class="token string">f"Value is </span><span class="token interpolation"><span class="token punctuation">{</span>value<span class="token punctuation">}</span></span><span class="token string">"</span></span> <span class="token comment"># Using the function with exception handling</span> <span class="token keyword">try</span><span class="token punctuation">:</span> result <span class="token operator">=</span> check_value<span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">5</span><span class="token punctuation">)</span> <span class="token keyword">print</span><span class="token punctuation">(</span>result<span class="token punctuation">)</span> <span class="token keyword">except</span> CustomError <span class="token keyword">as</span> e<span class="token punctuation">:</span> <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string-interpolation"><span class="token string">f"Caught an exception: </span><span class="token interpolation"><span class="token punctuation">{</span>e<span class="token punctuation">.</span>message<span class="token punctuation">}</span></span><span class="token string">"</span></span><span class="token punctuation">)</span></div>
</div>
<h3>Output</h3>
<p>On executing the above code we will get the following <strong>output</strong> &minus;</p>
<pre class="result notranslate">Caught an exception: Value cannot be negative!
</pre>
<div class="library-page-bottom-nav ">&nbsp;</div>
<div class="bottom-library-ads mt" style="margin: 5px;">
<div id="google-bottom-ads" class="google-bottom-ads">
<div style="width: 728px; height: 250px;">&nbsp;</div>
</div>
</div>